In [1]:
import torch
import numpy as np

In [3]:
#3 satır ve 5 süundan oluşan bir matriks oluşturur ve bu random sayılardan oluşur 0 ile 1 arasında
random_array=np.random.rand(3,5)
print(random_array)

[[0.43841223 0.05421214 0.20595871 0.30205076 0.37842807]
 [0.26188796 0.27590141 0.64745738 0.5330259  0.59995098]
 [0.20115424 0.14640128 0.32192203 0.6061546  0.16975446]]


In [6]:
# 0 ile 10 arasında 3*5 matrix oluşturdu
random_matrix=torch.randint(10,size=(3,5))
print(random_matrix)

tensor([[1, 3, 6, 0, 6],
        [0, 9, 3, 9, 3],
        [7, 7, 3, 7, 1]])


In [7]:
type(random_matrix)

torch.Tensor

In [9]:
random_matrix.ndim #kaç boyutlu olduğu hakkında

2

In [11]:
zeros=torch.zeros(size=(3,2))
print(zeros)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [12]:
ones=torch.ones(size=(3,2))
print(ones)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [16]:
#kaçtan başlıcak, kaça kadar gidicek ve adım sayımız nedir. 
vector_with_arand=torch.arange(3,10,1) # 3 dahil ama 10 dahil değil olacak
print(vector_with_arand)

tensor([3, 4, 5, 6, 7, 8, 9])


In [18]:
similar_ones=torch.ones_like(input=vector_with_arand) #girdiğin tensoru 1 ile doldurarak yazıyor
print(similar_ones)

tensor([1, 1, 1, 1, 1, 1, 1])


In [19]:
x_tensor=torch.tensor([1,2,3])
print(x_tensor)

tensor([1, 2, 3])


In [22]:
x_tensor+15 #her değere +15 eklemiş oluyorum tüm matematiksel işlemlerde geçerli oluyor

tensor([16, 17, 18])

In [24]:
x_tensor * x_tensor #bu şekilde de tüm matematiksel işlemleri yaparız ancak boyutlar eşleşmeli

tensor([1, 4, 9])