In [1]:
import torch
import numpy as np

In [2]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

In [3]:
matrix*matrix #bu dümdüz aynı yerdeki sayıları birbiri ile çarpmak için

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [5]:
matrix @ matrix  # @ işareti koyarsak işte bu gerçekte olan matrix çarpımı işlemini yapar

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [6]:
torch.matmul(matrix,matrix) #torchdaki karşılığı budur matrix multiplication

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [7]:
matrix.shape

torch.Size([3, 3])

In [8]:
tensor2 = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]])

In [9]:
tensor2.T  #lineer cebirden bildiğim transpose kavramı budur. sütunları satıra çeviriyor

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])