In [3]:
import torch
import numpy as np

In [4]:
tensor1=torch.arange(0,45,5)
tensor1

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [5]:
tensor1.min()

tensor(0)

In [6]:
tensor1.sum()

tensor(180)

In [7]:
tensor1.median()

tensor(20)

In [8]:
# tensor1.mean() #yapınca hesaplayamıyor ortalamasını saçma şekilde hata veriyor

In [9]:
tensor1=tensor1.type(torch.float) #floata çevirince hata vermiyor mean fonku

In [10]:
tensor1.mean() 

tensor(20.)

In [11]:
tensor1.argmax() #en yüksek değerin indeksini verir. index matığıburda da aynı şekilde çalışır

tensor(8)

In [12]:
tensor1[8]

tensor(40.)

In [13]:
#manipulating tensor: reshaping, stacking, squeezing, unsqueezing

In [14]:
x=torch.arange(1,10,1)
print(x)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [16]:
x.shape

torch.Size([9])

In [20]:
x.ndim  #1 boyutlu olacak yani

1

In [30]:
x_reshaped=x.reshape(1,9)  #boyutunu bu özel fonk ile yeniden  tanımlamış oldum

In [31]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [32]:
x_reshaped.ndim

2

In [38]:
x_reshaped=x.reshape(3,3)
print(x_reshaped)  #eleman saysını sağladığı için 3*3 bir matriks oluşturmuş oldum.

tensor([[20, 20, 20],
        [ 4,  5,  6],
        [ 7,  8,  9]])


In [35]:
# view diye bir konu var ve bu sayede tensor içindeki verileri değiştirebiliyorum

In [43]:
x_reshaped[0][2]=15  #bununla istenen kısmı değiştiriyorum hatta orijinal olan x'de de veri değişiyor
print(x_reshaped)

tensor([[20, 20, 15],
        [ 4,  5,  6],
        [ 7,  8,  9]])


In [52]:
x

tensor([20, 20, 15,  4,  5,  6,  7,  8,  9])

In [53]:
# contigioss tensor -> verileri bellekte,ramde art arta saklanan tensor çeşididir.

In [54]:
x.is_contiguous()

True

In [63]:
x=torch.tensor([[1,2,3],
               [4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [64]:
y=x.t()

In [65]:
print(y)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [67]:
y.is_contiguous()  #transpose yapılan tensorlar contigious olmuyorlar.

False