In [1]:
import torch
import numpy as np

In [2]:
tensor1=torch.arange(0,45,5)
tensor1

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [3]:
tensor1.min()

tensor(0)

In [4]:
tensor1.sum()

tensor(180)

In [5]:
tensor1.median()

tensor(20)

In [6]:
# tensor1.mean() #yapınca hesaplayamıyor ortalamasını saçma şekilde hata veriyor

In [7]:
tensor1=tensor1.type(torch.float) #floata çevirince hata vermiyor mean fonku

In [8]:
tensor1.mean() 

tensor(20.)

In [9]:
tensor1.argmax() #en yüksek değerin indeksini verir. index matığıburda da aynı şekilde çalışır

tensor(8)

In [10]:
tensor1[8]

tensor(40.)

In [11]:
#manipulating tensor: reshaping, stacking, squeezing, unsqueezing

In [12]:
x=torch.arange(1,10,1)
print(x)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [13]:
x.shape

torch.Size([9])

In [14]:
x.ndim  #1 boyutlu olacak yani

1

In [15]:
x_reshaped=x.reshape(1,9)  #boyutunu bu özel fonk ile yeniden  tanımlamış oldum

In [16]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [17]:
x_reshaped.ndim

2

In [18]:
x_reshaped=x.reshape(3,3)
print(x_reshaped)  #eleman saysını sağladığı için 3*3 bir matriks oluşturmuş oldum.

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [19]:
# view diye bir konu var ve bu sayede tensor içindeki verileri değiştirebiliyorum

In [20]:
x_reshaped[0][2]=15  #bununla istenen kısmı değiştiriyorum hatta orijinal olan x'de de veri değişiyor
print(x_reshaped)

tensor([[ 1,  2, 15],
        [ 4,  5,  6],
        [ 7,  8,  9]])


In [21]:
x

tensor([ 1,  2, 15,  4,  5,  6,  7,  8,  9])

In [22]:
# contigioss tensor -> verileri bellekte,ramde art arta saklanan tensor çeşididir.

In [23]:
x.is_contiguous()

True

In [24]:
x=torch.tensor([[1,2,3],
               [4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [25]:
y=x.t()

In [26]:
print(y)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [27]:
y.is_contiguous()  #transpose yapılan tensorlar contigious olmuyorlar. sıralı olarak saklanmıyorlar artık yani

False

In [28]:
#Bir tensorün transpose'unu aldığımızda ($A^T$), PyTorch veriyi bellekte yeniden düzenlemek yerine 
# sadece shape ve stride değerlerini takas eder (swap). Bu işlem $O(1)$ maliyetindedir, 
# yani çok hızlıdır.

In [29]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [30]:
#squezee and unsquezee

In [31]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.squeeze() #bakınca bir şey değişmemiş gibi görünüyor ancak eğer silebileceği bir boyut varsa siler. 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
x = torch.tensor([[1,2,3]])

In [36]:
x.ndim

2

In [41]:
x.squeeze().ndim #bak mesela 1 boyutu silmiş oldu. 

1

In [42]:
x.ndim

2

In [43]:
#unsqueeze de ise bir boyut daha ekleniyor.

In [46]:
#permute matrixteki sütunların yerlerini değişiyor 

In [47]:
x=torch.rand(size=[224,224,3])

In [50]:
x.shape #sondaki 3 (kırmızı yeşil mavi) kısmını bir model önde görmek istedi diyelim burda onu öne almak lazım

torch.Size([224, 224, 3])

In [54]:
x_permuted=x.permute(2,0,1) #hangilerinin hangi sırayla geleceğini gösterdik yani 2. index 0 a gelsin dedik

In [56]:
x_permuted.shape #bilgi kaybı yok sadece tekrardan boyutlandırdık

torch.Size([3, 224, 224])

In [57]:
#indexing and slicing

In [68]:
b=torch.arange(1,10,1)

In [69]:
b

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
b=b.reshape(1,3,3) #reshape ile de 1 boyut ekleyebiliyorum. squezee yapabiliyorum yani

In [80]:
b

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [76]:
b[0, :, 0]

tensor([1, 4, 7])

In [79]:
b[:,0,0]  # : demek tüm değerleri al demek, ilk sıfır row, ikincisi ise sütun

tensor([1])

In [81]:
b[:,1,1]

tensor([5])

In [83]:
b[:,:,0] #ilk ikisinde her şeyi al son olarak 0. sütunu al

tensor([[1, 4, 7]])

In [84]:
#random seed

In [87]:
RANDOM_SEED = 25
torch.manual_seed(RANDOM_SEED) #bunun sayesinde aynı değerleri vermesini sağlıyorum.
mytorch=torch.rand(3,4)
mytorch

tensor([[0.7518, 0.1929, 0.0629, 0.9118],
        [0.3828, 0.2990, 0.5933, 0.2911],
        [0.2416, 0.5582, 0.0481, 0.3497]])